# Generated by Django 4.2.21 on 2025-06-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroomApp', '0009_managernotification_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attended_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ATTENDED', 'Attended'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10),
        ),
    ]
