# Generated by Django 4.2.21 on 2025-06-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroomApp', '0012_remove_managernotification_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ATTENDED', 'Attended'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
