# Generated by Django 4.2.21 on 2025-06-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroomApp', '0013_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='noted_by',
            field=models.ManyToManyField(blank=True, related_name='noted_announcements', to='GroomApp.employee'),
        ),
    ]
