# Generated by Django 4.2.21 on 2025-06-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroomApp', '0015_suggestion_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='training',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
