# Generated by Django 4.2 on 2025-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroomApp', '0017_emailconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
